version: "3"
services:
  postgres:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./data/postgres:/var/dist/postgresql/data
